export const LOADING = "LOADING";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const AUTH_USER = "AUTH_USER";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const PRODUCTS_SEARCH_RESULTS = "PRODUCTS_SEARCH_RESULTS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_TOP_MOST_CATEGORIES = "GET_TOP_MOST_CATEGORIES";
export const GET_CATEGORIES_BY_PARENT_ID = "GET_CATEGORIES_BY_PARENT_ID";
